# Generated by Django 5.1.7 on 2025-03-09 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=20)),
                ('semester', models.CharField(max_length=20)),
                ('division', models.CharField(max_length=20)),
                ('roll', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=10)),
                ('dob', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('teacher', models.CharField(blank=True, max_length=100, null=True)),
                ('photo_sample', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
