services:
  - type: web
    name: biomark
    env: docker
    plan: free
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: biomark-db
          property: connectionString

databases:
  - name: biomark-db
    plan: free

